### ISSUE TITLE
All prefabs in demo scene are shown as "Missing prefab"

### ISSUE THREAD

**Issue by andybak** [Scrawk/Ceto#2]
Git clone of master. Opened in Unity 2018.3.5f1 (ProjectVersion.txt says original Unity version was 2018.3.4f1)

**Comment by friuns2** [comment]
import Ceto_1_1_4.unitypackage from the root folder, then it gets fixed

**Comment by Scrawk** [comment]
I think the project is missing something that allows Unity to clone it correctly. Not sure atm, maybe the meta files?

Im looking into it.

**Comment by andybak** [comment]
Yeah. gitexcluding .meta files would do it. They are absolutely essential. (also worth checking you've got serialization mode set to "force text" in settings - it makes things work much nicer with most VCS's)

**Comment by Scrawk** [comment]
I had force text and visible meta files enabled and thought that would do it but looks like the git ignore file defaults to ignoring meta files. 

They have been added now and looks like cloning is working.
