### ISSUE TITLE
HDRP Support

### ISSUE THREAD

**Issue by erherhh4herh** [Scrawk/Ceto#3]
This shader is really high quality and fidelity! I really enjoy this asset, it's well made! Because it's geared towards high fidelity graphics, could you support HDRP? That would be absolutely insane! Thanks!

**Comment by Scrawk** [comment]
This is actual a old asset that has been made open source. Its unlikely any further work will be done to it.

**Comment by erherhh4herh** [comment]
Aww okay, understood! Hopefully forks will be made :P
