### ISSUE TITLE
Ceto Wave Spectrum GPU Buffer Error

### ISSUE THREAD

**Issue by 3dship** [Scrawk/Ceto#4]
Hello
I am using Unity v2019.1.1f, when i open the demo scene i am getting this error:
Please can we solve this ?
thank you

Destroying object "Ceto Wave Spectrum GPU Buffer" is not allowed at this time.
UnityEngine.Object:Destroy(Object)
Ceto.Common.Unity.Utility.RTUtility:ReleaseAndDestroy(IList`1) (at Assets/Ceto/Scripts/Common/Unity/RTUtility.cs:205)
Ceto.WaveSpectrumBufferGPU:Release() (at Assets/Ceto/Scripts/Spectrum/Buffers/WaveSpectrumBufferGPU.cs:161)
Ceto.WaveSpectrum:Release() (at Assets/Ceto/Scripts/Spectrum/WaveSpectrum.cs:435)
Ceto.WaveSpectrum:OnDestroy() (at Assets/Ceto/Scripts/Spectrum/WaveSpectrum.cs:405)

**Comment by Scrawk** [comment]
Fixed now.
